### PR TITLE
only autoplay twitch player if not on touchscreen

### PR DESCRIPTION
**Pull request by rysllvn**
want to test on the dev edgio deployment. The idea to check this way is from https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent `Use [Navigator.maxTouchPoints](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/maxTouchPoints) to detect if the user's device has a touchscreen.`

https://github.com/cohstats/coh3-stats/issues/149

### CODE REVIEW

**Comment by petrvecera** [comment]
@rysllvn hm we can have laptops with touch screen. 

But we could improve the touchsreen with some additional check for userAgent https://stackoverflow.com/a/11381730/1768843

What about something like this:
```
isDesktop(){
return window.navigator.maxTouchPoints === 0  || (window.navigator.maxTouchPoints !== 0 && navigator.userAgentData.mobile === false)
}
```
Which should improve the coverage. 


OR

We could use the mediaQuery, that's how we determine elsewhere in the app if it's mobile or not https://mantine.dev/core/media-query/ (based on the size of screen) 

👍

**Comment by rysllvn** [comment]
That is a good point about tablets with touch screens. Also breaking it out into a function is good so that it acts as a comment.

I added a util function from the link you posted. https://stackoverflow.com/questions/11381673/detecting-a-mobile-browser/11381730#11381730

After thinking about it more to me this makes the most sense to me at least.

`userAgentData` does not exist on my browser at least. And I think checking screen width will not work with some phones these days such as the Samsung s21 ultra which has a 1440 width screen. I think a false positive for being on desktop is worse than the other way.

I think that really long regex though is well researched. Let me know what you think. The only way this doesn't work is if someone modifies their user agent on their phone, but then that would be a pretty advanced user and extreme edge case.

**Comment by petrvecera** [comment]
Btw the `1440 width screen` is reported by the phone? Browser should report scaled resolution. For example on my m1 mac, ma width is reported as 1512 although my actual width 3456 pixels. 

But I think it's fine for this use case 👍 

For other features on the site / such as layout changes it's better to use the width because you want that to change even on desktop, when someone resizes the window.

**Review by petrvecera — APPROVED** [review]

**Comment by rysllvn** [comment]
Okay you are probably right about the reported width. I definitely agree for most features like layout width is the most important thing because its about how the site looks.

The reason I'm thinking differently for this one is that the main concern is users' data plans. So whatever is most likely to catch all users on mobile and stop it from playing is best in my opinion.

**Review by petrvecera — APPROVED** [review]

**Pull request merged**
