### PR TITLE
About page

### PR DESCRIPTION
**Pull request by MarkTallentire**
Added menu as per #29 

Do we have any content written for other sections? 
Comparing to Aoe4world they have quite a bit of content under each section whereas right now we only have a basic about page for the site itself, added some placeholder tabs for now so you can see the current design but if we have some content I can add that.

Screenshot 2023-10-05 at 10 53 13

### CODE REVIEW

**Comment by MarkTallentire** [comment]
Also just realised that the original request was for it to Anchor and Scroll, let me know if you're happy with it switching the way it does or if you want it changed to auto scrolling anchors.

**Comment by petrvecera** [comment]
Hi, thanks for the submission. As you said I do have some text which I would like to write on that page but it's not that much. So that's also the reason why I wanted to have it more on one page, with some scrolls and anchors. I am afraid that for tabs it's not enough content. 

Would you be able to do it like that? 

Thank you 🙏

**Comment by MarkTallentire** [comment]
Updated to Anchors and scrolling

**Comment by petrvecera** [comment]
Nice 👍 I am gonna add the texts on master. Thank you 🙏

**Review by petrvecera — APPROVED** [review]

**Pull request merged**
