### PR TITLE
make sidemenu sticky in about us page

### PR DESCRIPTION
**Pull request by RajVerma97**
About - Menu not sticking #557

### MOBILE
Screenshot 2024-10-02 at 3 06 24 AM

### PC

Screenshot 2024-10-02 at 3 06 18 AM

### CODE REVIEW

**Review by petrvecera — APPROVED** [review]
Nice, I didn't know there is affix component :O

**Comment by RajVerma97** [comment]
> Nice, I didn't know there is affix component :O

Had to look up in the docs of mantine,there luckily  i found one.😅

**Comment by petrvecera** [comment]
Btw unfortunately the affix didn't work well on the very big screen, the menu was on the very left side of the screen. So if someone would open it on the 21:9 screen it would jump to the very left side. 

So I changed it to:
```
<div
  style={{
    position: "sticky", // to use sticky 
    top: 150,   // to use TOP 
    display: "block",
    height: "auto",
  }}
>
```

Which makes it stick to the middle side. But the affix is cool component.

**Comment by RajVerma97** [comment]
> Btw unfortunately the affix didn't work well on the very big screen, the menu was on the very left side of the screen. So if someone would open it on the 21:9 screen it would jump to the very left side.
> 
> So I changed it to:
> 
> ```
> <div
>   style={{
>     position: "sticky", // to use sticky 
>     top: 150,   // to use TOP 
>     display: "block",
>     height: "auto",
>   }}
> >
> ```
> 
> Which makes it stick to the middle side. But the affix is cool component.

got it

**Pull request merged**
