### PR TITLE
Add system colorscheme preference detection

### PR DESCRIPTION
**Pull request by JohannesMerkt**
https://github.com/cohstats/coh3-stats/issues/60

### CODE REVIEW

**Comment by petrvecera** [comment]
I wonder how this is going to look like

**Comment by JohannesMerkt** [comment]
Basically on first visit of the site the system colortheme is used and stored as default in localstorage. when a user changes the colorscheme preference it will be changed in localstorage for future visits

**Comment by petrvecera** [comment]
Huh if the branch name is too long - the permalink doesn't work :O 
https://coh-stats-coh3-stats-add-system-colorscheme-preferen-059164-135.alt.free.layer0-perma.link/
or https://preview.coh3stats.com/ ( but this one gets replace with every new MR) 


But anyway 
image


it looks like it doesn't work on my system. I am still getting light theme 
image

I tried deleting all the site data in dev tools.

**Comment by JohannesMerkt** [comment]
Yes doesnt work for me either ok dont merge yet

**Comment by petrvecera** [comment]
image
But here it works. Btw also if you could please change it to:
- Default "dark"  ( so the SSR is also dark) 
- If system detects white, switch to white

I would like the dark to be default. 

Thanks :)

**Comment by JohannesMerkt** [comment]
@petrvecera alright now it should work. 

Due to serverside rendering the useColorScheme hook always returned light theme. Changed it to always return dark theme.
But since we want users colorscheme preference we have to wait after the serverside rendering to detect the actual system colorscheme. this has been done now. when the user first visits the site the colorscheme cookie will be initialized to the system colorscheme preferences

**Pull request merged**
