### PR TITLE
Add Leaderboards to Frontpage

### PR DESCRIPTION
**Pull request by MarkTallentire**
Taken from issue:

> This one is actually a bit harder than it looks.
> 
> I made a start but there's quite a bit of moving things around to get to here, I then got a bit stuck on getting the data to it (I'm a Vue developer mainly so never used Next.js)
> 
> I'm not going to claim this and say I'll definitely do it because of my work commitments so if someone wants to pick it up still, feel free. If anyone well versed in Next JS wants to pick it up you should just be able to pass the props to the new component components\leaderboards\leaderboards-table.tsx on my fork and be pretty much done minus a bit of cleanup of the index and leaderboards screen files.

Todo:

- Move component out of `components/screens/home/index.tsx`
- Provide the correct data to `components/leaderboards/leaderboards-table.tsx` - Will need to pass only the top 10 or get creative with recordsperpage and hiding the pagination (obviously slower vs just changing the data request number)
- Add link to the full leaderboards in the bottom right (As a first draft this can maybe just go to the main leaderboards page but it should consider the current leaderboard being viewed)
- Prop types `components/leaderboards/leaderboards-table.tsx`
- Find a new location for the donation buttons
- Based on issue #10 - propose that we make this a 3quarter or half width panel and put the reddit cards next to it. Again similar to https://aoe4world.com/

### CODE REVIEW

**Comment by petrvecera** [comment]
Btw I would create a new component for the leaderboards table on the main page. Because we might want to display the data differently (less information). Or we could modify that component to have 2 version. One for front page, second for the leaderboards. I am not sure what could be better - duplication of some code VS more spaghetti code in one component. 

I will look at this later and update it with the data fetching.

**Comment by MarkTallentire** [comment]
> Btw I would create a new component for the leaderboards table on the main page. Because we might want to display the data differently (less information). Or we could modify that component to have 2 version. One for front page, second for the leaderboards. I am not sure what could be better - duplication of some code VS more spaghetti code in one component.
> 
> I will look at this later and update it with the data fetching.

Yeah, i considered this at the time. I think a new component is probably better, the new one will be a bit more lightweight as it doesnt have to deal with paging etc. As the overall look and feel of the leaderboards is unlikely to ever change I don't think having 2 components is a terrible idea.

**Comment by petrvecera** [comment]
@MarkTallentire I create a branch `Leaderboards-frontpage-data-fetch` where I have implemented the datafetching https://github.com/cohstats/coh3-stats/pull/246/files

Could you try to pull that branch into your branch?

**Comment by MarkTallentire** [comment]
Okay pretty happy with this now. thank you for doing the data pull.

The only thing I have considered and tried to make work is on Mobile the names could be shortened so the wrap isnt as obvious on the flex box

image

DAK is obviously the big offender here so wanted to shorten to ["British, "US", "DAK", "Wehr"] but I cant get isMobileCheck to work for me from utils. I assume it has something to do with NextJS being SSR

Another thing to consider is making this render more dynamically based on a list of factions instead of repeating `<Tabs.Tab value="british">British Forces</Tabs.Tab>` or it may bite when/if an expansion is released

**Review by petrvecera — APPROVED** [review]
Looks great 👍  Thank you very much. 

For the mobile / large view it's better to use media query like this 
https://github.com/cohstats/coh3-stats/blob/master/components/charts/card-factions-heatmap.tsx#L68C9-L68C21

https://mantine.dev/hooks/use-media-query/

The utils isMobile is more useful to detect if you are "mobile" and for example you want do disable a data heavy loads or something like that. But otherwise it's better to act based on the screen size.

**Pull request merged**
